# Site settings
title:          Kakao Enterprise AI Lab
description:    "Kakao Enterprise AI Lab"
url:            "https://pages.github.kakaocorp.com/ailab-papers"

# Author
author:
  name:         Kakao Enterprise AI Lab
  email:        ailab-papers@kakaoenterprise.com

# Build settings
markdown:       kramdown
include:
  - _pages
future:         true

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:slug
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, vendor, serve.sh ]
